# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Include include_high_availability_config.yml vars
  block:
    - name: Include include_high_availability_config vars
      ansible.builtin.include_vars: "{{ ha_config_file }}"
      register: include_ha_config
      no_log: true
  rescue:
    - name: Failed to include_high_availability_config.yml
      ansible.builtin.fail:
        msg: "{{ ha_config_syntax_fail_msg }} Error: {{ include_ha_config.message }}"
