# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Include telemetry_config_file.yml
- name: Check that the telemetry_config.yml exists
  ansible.builtin.stat:
    path: "{{ telemetry_config_file }}"
  register: stat_result

- name: Fail if telemetry_config.yml file doesn't exist
  ansible.builtin.fail:
    msg: "{{ fail_msg_telemetry_config_file }}"
  when: not stat_result.stat.exists

- name: Check telemetry_config.yml file is encrypted
  ansible.builtin.command: cat {{ telemetry_config_file }}
  changed_when: false
  register: config_content
  no_log: true

- name: Decrpyt telemetry_login_vars.yml
  ansible.builtin.command: >-
    ansible-vault decrypt {{ telemetry_config_file }}
    --vault-password-file {{ vault_filename }}
  changed_when: false
  when: "'$ANSIBLE_VAULT;' in config_content.stdout"

- name: Include variable file telemetry_config.yml
  block:
    - name: Include variable file telemetry_config.yml
      ansible.builtin.include_vars:
        file: "{{ telemetry_config_file }}"
        name: telemetry_config
      register: include_telemetry_config
      no_log: false
  rescue:
    - name: Failed to include telemetry_config.yml
      ansible.builtin.fail:
        msg: "{{ telemetry_config_syntax_fail_msg }} Possible Syntax Error Hints: {{ include_telemetry_config.message }}"

- name: Set support values
  ansible.builtin.set_fact:
    idrac_telemetry_support: "{{ telemetry_config.idrac_telemetry_support | lower }}"
    omnia_telemetry_support: "{{ telemetry_config.omnia_telemetry_support | lower }}"
    visualization_support: "{{ telemetry_config.visualization_support | lower }}"
    k8s_prometheus_support: "{{ telemetry_config.k8s_prometheus_support | lower }}"
    prometheus_gaudi_support: "{{ telemetry_config.prometheus_gaudi_support | lower }}"
    timescaledb_user: "{{ telemetry_config.timescaledb_user | default('') }}"
    timescaledb_password: "{{ telemetry_config.timescaledb_password | default('') }}"
    idrac_username: "{{ telemetry_config.idrac_username | default('') }}"
    idrac_password: "{{ telemetry_config.idrac_password | default('') }}"
    mysqldb_user: "{{ telemetry_config.mysqldb_user | default('') }}"
    mysqldb_password: "{{ telemetry_config.mysqldb_password | default('') }}"
    mysqldb_root_password: "{{ telemetry_config.mysqldb_root_password | default('') }}"
    collect_regular_metrics: "{{ telemetry_config.collect_regular_metrics | default(true) }}"
    collect_health_check_metrics: "{{ telemetry_config.collect_health_check_metrics | default(true) }}"
    collect_gpu_metrics: "{{ telemetry_config.collect_gpu_metrics | default(true) }}"
    grafana_username: "{{ telemetry_config.grafana_username | default('') }}"
    grafana_password: "{{ telemetry_config.grafana_password | default('') }}"
    mount_location: "{{ telemetry_config.mount_location | default('') }}"

- name: Assert idrac telemetry support
  ansible.builtin.assert:
    that:
      - idrac_telemetry_support == true or idrac_telemetry_support == false
    success_msg: "{{ idrac_telemetry_support_success_msg }}"
    fail_msg: "{{ idrac_telemetry_support_fail_msg }}"

- name: Assert omnia telemetry support
  ansible.builtin.assert:
    that:
      - omnia_telemetry_support == true or omnia_telemetry_support == false
    fail_msg: "{{ omnia_telemetry_support_fail_msg }}"

- name: Assert visualization support
  ansible.builtin.assert:
    that:
      - visualization_support == true or visualization_support == false
    success_msg: "{{ visualization_support_success_msg }}"
    fail_msg: "{{ visualization_support_fail_msg }}"

- name: Assert k8s prometheus support
  ansible.builtin.assert:
    that:
      - k8s_prometheus_support == true or k8s_prometheus_support == false
    success_msg: "{{ k8s_prometheus_support_success_msg }}"
    fail_msg: "{{ k8s_prometheus_support_fail_msg }}"

- name: Assert prometheus gaudi support
  ansible.builtin.assert:
    that:
      - prometheus_gaudi_support == true or prometheus_gaudi_support == false
    success_msg: "{{ prometheus_gaudi_support_success_msg }}"
    fail_msg: "{{ prometheus_gaudi_support_fail_msg }}"

- name: Warning for all telemetry support category values set as false
  ansible.builtin.pause:
    seconds: "{{ pause_time_15 }}"
    prompt: "{{ warning_telemetry_support_false }}"
  when:
    - not idrac_telemetry_support
    - not omnia_telemetry_support
    - not visualization_support
    - not k8s_prometheus_support
    - not prometheus_gaudi_support

- name: Please wait, This task will take few seconds
  ansible.builtin.pause:
    seconds: "{{ idrac_omnia_telemetry_support_false_warn_time }}"
    prompt: "{{ idrac_omnia_telemetry_support_warn_msg }}"
  when:
    - not idrac_telemetry_support
    - not omnia_telemetry_support
    - not k8s_prometheus_support
    - not prometheus_gaudi_support

- name: Assert usernames and passwords in telemetry_login_vars.yml
  when: idrac_telemetry_support or omnia_telemetry_support
  block:
    - name: Assert timescaledb user name
      ansible.builtin.assert:
        that:
          - timescaledb_user | length > 1
          - '"-" not in timescaledb_user '
          - '"\\" not in timescaledb_user '
          - '"\"" not in timescaledb_user '
          - " \"'\" not in timescaledb_user "
      no_log: true

    - name: Assert timescaledb user password
      ansible.builtin.assert:
        that:
          - timescaledb_password | length > 1
          - '"-" not in timescaledb_password '
          - '"\\" not in timescaledb_password '
          - '"\"" not in timescaledb_password '
          - " \"'\" not in timescaledb_password "
          - '"@" not in timescaledb_password '
      no_log: true

  rescue:
    - name: Validation issue in telemetry_config.yml
      ansible.builtin.fail:
        msg: "{{ login_vars_fail_msg }}"

# Include validations for idrac telemetry
- name: Validate idrac telemetry
  ansible.builtin.include_tasks: validate_idrac_telemetry.yml
  when: idrac_telemetry_support

# Include validations for omnia telemetry
- name: Validate omnia telemetry
  ansible.builtin.include_tasks: validate_omnia_telemetry.yml
  when: omnia_telemetry_support

- name: Include grafana validations
  ansible.builtin.include_tasks: validate_grafana_params.yml
  when: visualization_support

- name: Validate k8s prometheus, scrape interval and prometheus gaudi
  ansible.builtin.include_tasks: validate_k8s_prometheus_prometheus_gaudi.yml
  when: k8s_prometheus_support or prometheus_gaudi_support

- name: Validate k8s prometheus when prometheus gaudi is true
  ansible.builtin.include_tasks: validate_prometheus_gaudi.yml
  when: prometheus_gaudi_support

# Validate k8s inputs
- name: Assert k8s_cni
  ansible.builtin.assert:
    that:
      - telemetry_config.k8s_cni == "calico" or telemetry_config.k8s_cni == "flannel"
    fail_msg: "{{ invalid_k8s_cni }}"

- name: Assert pod external IP range
  ansible.builtin.assert:
    that:
      - telemetry_config.pod_external_ip_range | default("", true) | length > 9
      - ("'/' in telemetry_config.pod_external_ip_range") or ("'-' in telemetry_config.pod_external_ip_range")
    fail_msg: "{{ invalid_pod_external_ip_range }}"
  when: idrac_telemetry_support or omnia_telemetry_support or visualization_support

- name: Assert kubernetes service addresses
  ansible.builtin.assert:
    that:
      - telemetry_config.k8s_service_addresses | default("", true) | length > 9
      - '"/" in telemetry_config.k8s_service_addresses'
    fail_msg: "{{ invalid_k8s_service_addresses }}"

- name: Assert kubernetes pod network CIDR
  ansible.builtin.assert:
    that:
      - telemetry_config.k8s_pod_network_cidr | default("", true) | length > 9
      - '"/" in telemetry_config.k8s_pod_network_cidr'
    fail_msg: "{{ invalid_k8s_pod_network_cidr }}"

# Encrypt telemetry_config.yml
- name: Create ansible vault key
  ansible.builtin.set_fact:
    vault_key: "{{ lookup('password', '/dev/null chars=ascii_letters') }}"
  when: "'$ANSIBLE_VAULT;' not in config_content.stdout"

- name: Save vault key
  ansible.builtin.lineinfile:
    path: "{{ vault_filename }}"
    line: "{{ vault_key }}"
    mode: "{{ vault_file_perm }}"
    owner: root
    create: true
  when: "'$ANSIBLE_VAULT;' not in config_content.stdout"

- name: Encrypt telemetry_config.yml file
  ansible.builtin.command: >-
    ansible-vault encrypt {{ telemetry_config_file }}
    --vault-password-file {{ vault_filename }}
  changed_when: false
