# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: main.yml
xcat_path: /opt/xcat/bin

# Usage: configure_kickstart.yml
xcat_rhel8_tmpl: "/opt/xcat/share/xcat/install/rh/compute.rhels8.tmpl"
xcat_rhel8_post_script: "/opt/xcat/share/xcat/install/scripts/post.rhels8"

# Usage: disk_partition.yml
xcat_rhel8_pre_script: "/opt/xcat/share/xcat/install/scripts/pre.rhels8"
