# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

---

- name: Create PCS directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  loop: "{{ pcs_directories }}"

- name: Create pcs-start.sh and corosync.conf at PCS NFS share and the Quadlet file at the systemd directory
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop: "{{ pcs_startup_file }}"

- name: Check if {{ pcs_container_name }} container is running # noqa: name[template]
  containers.podman.podman_container_info:
    name: "{{ pcs_container_name }}"
  register: pcs_container_info
  failed_when: false

- name: Pull PCS image
  containers.podman.podman_image:
    name: "{{ pcs_image_name }}"
    tag: "{{ pcs_image_tag }}"
    state: present
  register: image_pull_result

- name: Fail if the PCS image pull fails
  ansible.builtin.fail:
    msg: "{{ pcs_image_pull_fail_msg }}"
  when: image_pull_result.failed

- name: Verify if PCS image exists
  containers.podman.podman_image_info:
    name: "{{ pcs_image_name }}:{{ pcs_image_tag }}"
  register: image_facts

- name: Fail if the PCS image is not found
  ansible.builtin.fail:
    msg: "{{ pcs_image_not_found_msg }}"
  when: not image_facts.images

- name: Remove the PCS resource finished file if it exists
  ansible.builtin.file:
    path: "{{ pcs_start_shared_finished }}"
    state: absent

- name: Deploy PCS container and check deployment status
  block:
    - name: Deploy the PCS container
      containers.podman.podman_container:
        name: "{{ pcs_container_name }}"
        image: "{{ pcs_image_name }}:{{ pcs_image_tag }}"
        state: present
        privileged: true
        network_mode: host
        volumes: "{{ pcs_volumes }}"
        cap_add:
          - AUDIT_WRITE
        restart_policy: always

    - name: Start the PCS container
      containers.podman.podman_container:
        name: "{{ pcs_container_name }}"
        state: started

    - name: Check if PCS container is running after deployment
      containers.podman.podman_container_info:
        name: "{{ pcs_container_name }}"
      register: pcs_container_status

    - name: Notify user of PCS container deployment status
      ansible.builtin.debug:
        msg: "{{ pcs_container_success_msg }}"
      when:
        - pcs_container_status.containers | length > 0
        - pcs_container_status.containers[0].State.Status == 'running'

  rescue:
    - name: PCS container deployment failed
      ansible.builtin.fail:
        msg: "{{ pcs_container_failure_msg }}"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start omnia_pcs service
  ansible.builtin.systemd:
    name: omnia_pcs
    state: started

- name: Validate pcs-start script completed and the created PCS resources are started
  block:
    - name: Wait for pcs-start.sh execution to complete
      ansible.builtin.wait_for:
        path: "{{ pcs_start_shared_finished }}"
        state: present
        timeout: "{{ wait_time_pcs_start }}"
        msg: "{{ pcs_start_failed_msg }}"
      register: wait_result

    - name: Add kubespray_name to pcs-resources if k8s_support is defined
      ansible.builtin.set_fact:
        pcs_resources: "{{ pcs_resources + [kubespray_name] }}"
      when: hostvars['localhost']['k8s_support']

    - name: Parse PCS resources for any that are not started
      ansible.builtin.shell: |
        set -o pipefail
        cat {{ pcs_start_shared_finished }} | grep "Stopped\|FAILED"
      args:
        executable: /bin/bash
      register: improper_resources
      failed_when: false
      changed_when: false

    - name: Fail if PCS any resource is stopped or failed
      ansible.builtin.fail:
        msg:
          - "PCS resource(s) in an improper state: {{ improper_resources.stdout_lines }}"
          - "{{ pcs_failed_resource_msg }}"
      when: improper_resources.stdout_lines | default([]) | length > 0

    - name: Parse all created PCS resources
      ansible.builtin.shell: |
        set -o pipefail
        cat {{ pcs_start_shared_finished }} | awk '{print $1}'
      args:
        executable: /bin/bash
      register: resources
      failed_when: false
      changed_when: false

    - name: Check if all pcs-start.sh resources were created
      ansible.builtin.set_fact:
        missing_resources: "{{ missing_resources | default([]) + [item] }}"
      loop: "{{ pcs_resources }}"
      when: item not in resources.stdout_lines

    - name: Fail if any resources are missing
      ansible.builtin.fail:
        msg:
          - "PCS resource(s) are missing: {{ missing_resources }}"
          - "{{ pcs_failed_resource_msg }}"
      when: missing_resources | default([]) | length > 0
