# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: main.yml
discovery_method_bmc: "bmc"
dhcp_timeout: 600
dhcp_timeout_msg: "[WARNING] Waiting for 10 minutes before starting dynamic discovery"
static_dynamic_fail_msg: "Failed. No BMC found for both static and dynamic IP's. Please check the ranges again."
dhcp_path: "/var/lib/dhcpd/dhcpd.leases"
xcat_path: /opt/xcat/bin

# Usage: bmc_discover_ranges.yml
static_ip_file: "/opt/omnia/provision/static.stanzas"
dynamic_ip_file: "/opt/omnia/provision/dynamic.stanzas"

stanza_paths:
  - "{{ static_ip_file }}"
  - "{{ dynamic_ip_file }}"
file_perm: "0644"
bmcdiscover_python: "{{ provision_shared_library_path }}/mtms/bmc_discover_ranges.py"
static_mode: "static"
dynamic_mode: "dynamic"

# Usage: update_xcat_network_discovery_range.yml
update_bmc_network_python: "{{ provision_shared_library_path }}/mtms/update_bmc_network.py"

# Usage: update_db.yml
update_db_static_path: "{{ provision_shared_library_path }}/mtms/mtms_db.py"
mtms_db_path: "{{ provision_shared_library_path }}/db_operations"

# Usage: update_db_dynamic.yml
update_db_dynamic_path: "{{ provision_shared_library_path }}/mtms/mtms_dhcp_db.py"

# Usage: update_node_obj.yml
update_node_obj_path: "{{ provision_shared_library_path }}/mtms/update_node_objects.py"
delete_nodes: "{{ provision_shared_library_path }}/mtms/delete_misc_node_obj.py"

# Usage: set_provision_image_mtms.yml
bmc_node_group: "bmc"
mtms_set_pxe_warning_msg: "[WARNING] Setting PXE boot failed for the discovered nodes using BMC. Error:"
mtms_xcat_install_success_msg: "Provision tasks executed successfully for discovered nodes using BMC."
mtms_poweron_warning_msg: "[WARNING] Power on failed for the discovered nodes using BMC. Error:"

# Usage: dynamic_ipmi_enable.yml
create_dynamic_ip_path: "{{ provision_shared_library_path }}/mtms/create_dynamic_ip_list.py"
dynamic_ip_list: "/opt/omnia/provision/dynamic_ip_list"
ipmi_command: 'racadm set iDRAC.IPMILan.Enable 1'
timeout_ipmi: 15
