#  Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Fetch facts for nodes including new nodes
  when:
    - hostvars['127.0.0.1']['k8s_support']
    - hostvars[groups['kube_control_plane'][0]]['k8s_installation_status']
    - hostvars[groups['kube_control_plane'][0]]['k8s_new_nodes'] != ''
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.facts
  vars:
    kube_version: "v{{ hostvars['localhost']['k8s_version'] }}"
    container_manager: "containerd"
    dashboard_enabled: true
    helm_enabled: true
    kube_network_plugin: "{{ hostvars['localhost']['omnia_config']['k8s_cni'] }}"
    kube_service_addresses: "{{ hostvars['localhost']['omnia_config']['k8s_service_addresses'] }}"
    kube_pods_subnet: "{{ hostvars['localhost']['omnia_config']['k8s_pod_network_cidr'] }}"
    kube_proxy_strict_arp: true
    kube_proxy_mode: 'iptables'
    kubelet_custom_flags: "{% if hostvars['localhost']['topology_manager_policy'] != 'none' %}
      --topology-manager-policy={{ hostvars['localhost']['topology_manager_policy'] }}
      --topology-manager-scope={{ hostvars['localhost']['topology_manager_scope'] }}
                          {% endif %}"
    metallb_enabled: true
    metallb_speaker_enabled: true
    metallb_namespace: "metallb-system"
    metallb_config:
      address_pools:
        primary:
          ip_range:
            - "{{ hostvars['localhost']['omnia_config']['pod_external_ip_range'] }}"
          auto_assign: true
      layer2:
        - primary
    override_system_hostname: false
    populate_inventory_to_hosts_file: false
    enable_nodelocaldns: false
    upstream_dns_servers:
      - "{{ hostvars['localhost']['admin_nic_ip'] }}"
    unsafe_show_logs: true
    kube_image_repo: "registry.k8s.io"
    docker_image_repo: "docker.io"
    quay_image_repo: "quay.io"
    containerd_registries_mirrors:
      - prefix: xyz.io
        mirrors:
          - host: https://mirror.gcr.io
            capabilities: ["pull", "resolve"]
            skip_verify: false
    kubeadm_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['kubeadm_package'] }}.tar.gz"
    kubectl_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['kubectl_package'] }}.tar.gz"
    kubelet_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['kubelet_package'] }}.tar.gz"
    crictl_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['crictl_package'] }}.tar.gz"
    calicoctl_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['calicoctl_package'] }}.tar.gz"
    calico_crds_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['calico_crds_package'] }}.tar.gz"
    cni_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['cni_package'] }}.tar.gz"
    nerdctl_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['nerdctl_package'] }}.tar.gz"
    runc_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['runc_package'] }}.tar.gz"
    docker_rh_repo_base_url: ""
    docker_rh_repo_gpgkey: ""
    etcd_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['etcd_package'] }}.tar.gz"
    containerd_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['containerd_package'] }}.tar.gz"
    helm_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['helm_package'] }}.tar.gz"
    http_proxy: "{{ hostvars['localhost']['http_proxy'] }}"
    https_proxy: "{{ hostvars['localhost']['https_proxy'] }}"
    no_proxy: "localhost,127.0.0.1,{{ hostvars['localhost']['admin_nic_ip'] }},{{ hostvars['localhost']['omnia_config']['k8s_service_addresses'] }},{{ hostvars['localhost']['omnia_config']['k8s_pod_network_cidr'] }},{{ hostvars['localhost']['omnia_config']['k8s_cni'] }},{{ hostvars['localhost']['oim_hostname'] }},{{ hostvars['localhost']['domain_name'] }}"   # noqa: yaml[line-length]
    additional_no_proxy: "{{ hostvars['localhost']['user_no_proxy'] if hostvars['localhost']['no_proxy_input_status'] else '' }}"   # noqa: yaml[line-length]

- name: Initiate add node
  when:
    - hostvars['127.0.0.1']['k8s_support']
    - hostvars[groups['kube_control_plane'][0]]['k8s_installation_status']
    - hostvars[groups['kube_control_plane'][0]]['k8s_new_nodes'] != ''
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.scale --limit="{{ hostvars[groups['kube_control_plane'][0]]['k8s_new_nodes'] }}"
  vars:
    kube_version: "v{{ hostvars['localhost']['k8s_version'] }}"
    container_manager: "containerd"
    dashboard_enabled: true
    helm_enabled: true
    kube_network_plugin: "{{ hostvars['localhost']['omnia_config']['k8s_cni'] }}"
    kube_service_addresses: "{{ hostvars['localhost']['omnia_config']['k8s_service_addresses'] }}"
    kube_pods_subnet: "{{ hostvars['localhost']['omnia_config']['k8s_pod_network_cidr'] }}"
    kubelet_custom_flags: "{% if hostvars['localhost']['topology_manager_policy'] != 'none' %}
      --topology-manager-policy={{ hostvars['localhost']['topology_manager_policy'] }}
      --topology-manager-scope={{ hostvars['localhost']['topology_manager_scope'] }}
                          {% endif %}"
    kube_proxy_strict_arp: true
    metallb_enabled: true
    metallb_speaker_enabled: true
    metallb_namespace: "metallb-system"
    metallb_config:
      address_pools:
        primary:
          ip_range:
            - "{{ hostvars['localhost']['omnia_config']['pod_external_ip_range'] }}"
          auto_assign: true
      layer2:
        - primary
    override_system_hostname: false
    populate_inventory_to_hosts_file: false
    enable_nodelocaldns: false
    upstream_dns_servers:
      - "{{ hostvars['localhost']['admin_nic_ip'] }}"
    unsafe_show_logs: true
    kube_image_repo: "registry.k8s.io"
    docker_image_repo: "docker.io"
    quay_image_repo: "quay.io"
    containerd_registries_mirrors:
      - prefix: xyz.io
        mirrors:
          - host: https://mirror.gcr.io
            capabilities: ["pull", "resolve"]
            skip_verify: false
    kubeadm_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['kubeadm_package'] }}.tar.gz"
    kubectl_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['kubectl_package'] }}.tar.gz"
    kubelet_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['kubelet_package'] }}.tar.gz"
    crictl_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['crictl_package'] }}.tar.gz"
    calicoctl_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['calicoctl_package'] }}.tar.gz"
    calico_crds_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['calico_crds_package'] }}.tar.gz"
    cni_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['cni_package'] }}.tar.gz"
    nerdctl_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['nerdctl_package'] }}.tar.gz"
    runc_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['runc_package'] }}.tar.gz"
    docker_rh_repo_base_url: ""
    docker_rh_repo_gpgkey: ""
    etcd_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['etcd_package'] }}.tar.gz"
    containerd_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['containerd_package'] }}.tar.gz"
    helm_download_url: "{{ hostvars['localhost']['offline_tarball_path'] }}/{{ hostvars['localhost']['helm_package'] }}.tar.gz"
    http_proxy: "{{ hostvars['localhost']['http_proxy'] }}"
    https_proxy: "{{ hostvars['localhost']['https_proxy'] }}"
    no_proxy: "localhost,127.0.0.1,{{ hostvars['localhost']['admin_nic_ip'] }},{{ hostvars['localhost']['omnia_config']['k8s_service_addresses'] }},{{ hostvars['localhost']['omnia_config']['k8s_pod_network_cidr'] }},{{ hostvars['localhost']['oim_hostname'] }},{{ hostvars['localhost']['domain_name'] }}"   # noqa: yaml[line-length]
    additional_no_proxy: "{{ hostvars['localhost']['user_no_proxy'] if hostvars['localhost']['no_proxy_input_status'] else '' }}"   # noqa: yaml[line-length]
