---
collections:
  - name: kubernetes.core
    version: 5.0.0
  - name: ansible.utils
    version: 5.1.1
  - name: community.crypto
    version: 2.23.0
  - name: community.docker
    version: 3.12.1
  - name: community.general
    version: 10.3.0
  - name: community.grafana
    version: 2.1.0
  - name: community.mysql
    version: 3.10.3
  - name: dellemc.os10
    version: 1.1.1
  - name: dellemc.openmanage
    version: 9.6.0
  - name: ansible.posix
    version: 2.0.0
  - name: containers.podman
    version: 1.16.2
  - name: community.postgresql
    version: 3.10.2
  - name: https://github.com/kubernetes-sigs/kubespray
    type: git
    version: v2.25.0
